In [3]:
import numpy as np
import pandas as pd

### 1️⃣ Create a 1D NumPy array of numbers from 0 to 9

In [5]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### 2️⃣ Create a 3x3 NumPy array filled with all True values

In [10]:
arr1 = np.ones((3,3))
arr2 = arr1.astype(bool)

print(arr1)
print("-------------------")
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 3️⃣ Extract all odd numbers from a given NumPy array

In [14]:
arr = np.arange(15)
odd = arr[arr % 2 != 0]
print(odd)

[ 1  3  5  7  9 11 13]


### 4️⃣ Replace all odd numbers in an array with -1

In [21]:
arr = np.arange(15)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14]


### 5️⃣ Create a 5x5 identity matrix

In [22]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 6️⃣ Create a 3x3 matrix with values ranging from 0 to 8 using np.arange

In [26]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 7️⃣ Reverse a 1D NumPy array (first element becomes last)

In [29]:
arr = np.arange(10)
rev = arr[::-1]
print(rev)

[9 8 7 6 5 4 3 2 1 0]


### 8️⃣ Reshape a 1D array of 10 elements into a 2D array with 2 rows

In [31]:
arr = np.arange(10).reshape(2,-1)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 9️⃣ Stack two NumPy arrays vertically and horizontally

In [38]:
a = np.arange(10).reshape(2,-1)
b = np.arange(10,20).reshape(2,-1)

v_stack = np.concatenate((a,b),axis = 0)
h_stack = np.concatenate((a,b),axis = 1)

print(a)
print("---------------")
print(b)
print("---------------")
print(v_stack)
print("---------------")
print(h_stack)

[[0 1 2 3 4]
 [5 6 7 8 9]]
---------------
[[10 11 12 13 14]
 [15 16 17 18 19]]
---------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
---------------
[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


### 🔟 Convert a Python list and a tuple into a NumPy array

In [39]:
lst = [1, 2, 3]
tpl = (4, 5, 6)

arr1 = np.array(lst)
arr2 = np.array(tpl)

print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


### 11 - Get common items between two arrays

In [40]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

common = np.intersect1d(a, b)
print(common)

[4 5]


### 12 - Remove all elements of one array from another array

In [41]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5])

result = np.setdiff1d(a, b)
print(result)

[1 2]


### 13 - Get positions (indices) where elements of two arrays match

In [42]:
a = np.array([1, 2, 3, 2, 4])
b = np.array([2, 2, 3, 2, 5])

indices = np.where(a == b)
print(indices)

(array([1, 2, 3]),)


### 14 - Generate a random float matrix of shape (3,3) between 0 and 1

In [43]:
arr = np.random.rand(3,3)
print(arr)

[[0.99765419 0.47696206 0.49013896]
 [0.66978266 0.64724753 0.08203756]
 [0.14947132 0.47423667 0.13669424]]


### 15 - Set the diagonal elements of a 5x5 matrix to zero without using loops

In [44]:
arr = np.ones((5,5))
np.fill_diagonal(arr,0)
print(arr)

[[0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]


# Intermediate Questions

### 1️⃣ Normalize a NumPy array (values between 0 and 1)

In [48]:
arr = np.linspace(10,100, 10).astype(int)
norm = ( arr - arr.min())/(arr.max() - arr.min())
print(norm.round(2))

[0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]


### 2️⃣ Standardize a NumPy array (zero mean, unit variance)

In [49]:
arr = np.array([10, 20, 30, 40, 50])
std = np.std(arr)
mean = np.mean(arr)

standard = ( arr - mean )/std
print(standard)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### 3️⃣ Find the mean, median, variance, and standard deviation of an array

In [50]:
arr = np.array([1, 2, 3, 4, 5])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

Mean: 3.0
Median: 3.0
Variance: 2.0
Standard Deviation: 1.4142135623730951


### 4️⃣ Get unique values, counts, and frequencies of elements in an array

In [56]:
arr = np.array([1, 2, 2, 3, 3, 3, 4])
unique,counts = np.unique(arr,return_counts=True)
freq = counts/len(arr)
freq

array([0.14285714, 0.28571429, 0.42857143, 0.14285714])

In [57]:
from collections import Counter
counter = Counter(arr)
counter

Counter({3: 3, 2: 2, 1: 1, 4: 1})

### 5️⃣ Replace NaN values in an array with the mean of that column

In [61]:
arr = np.array([[1, np.nan, 3], [4, 5, np.nan], [7, 8, 9]])
col_mean = np.nanmean(arr,axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean,inds[1])
print(arr)

[[1.  6.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


### 6️⃣ Compute column-wise and row-wise sums and means of a 2D array

In [63]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("----------")
print("Row-wise sum:", arr.sum(axis=1))
print("Column-wise sum:", arr.sum(axis=0))
print("Row-wise mean:", arr.mean(axis=1))
print("Column-wise mean:", arr.mean(axis=0))

[[1 2 3]
 [4 5 6]]
----------
Row-wise sum: [ 6 15]
Column-wise sum: [5 7 9]
Row-wise mean: [2. 5.]
Column-wise mean: [2.5 3.5 4.5]


### 7️⃣ Sort a NumPy array by the second column

In [64]:
arr = np.array([[1, 7, 3], [4, 2, 6], [9, 5, 1]])

sorted_arr = arr[arr[:, 1].argsort()]
print(sorted_arr)

[[4 2 6]
 [9 5 1]
 [1 7 3]]


### 8️⃣ Get the top 5 maximum values of a 1D array

In [67]:
arr = np.array([10, 90, 30, 70, 50, 20, 100])
top5 = np.sort(arr)
print(top5[-5:])

[ 30  50  70  90 100]


### 9️⃣ Find the most frequent value in an array

In [69]:
arr = np.array([1, 2, 2, 3, 3, 3, 4])
vals, counts = np.unique(arr, return_counts=True)
index = np.argmax(counts)
most_frequent = vals[index]
print(most_frequent)

3


### 🔟 Perform element-wise multiplication and matrix multiplication of two 2D arrays

In [70]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

elementwise = a * b
matmul = a @ b  # or np.dot(a, b)

print("Element-wise:\n", elementwise)
print("Matrix Multiplication:\n", matmul)

Element-wise:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


### 11️⃣ Compute the Euclidean distance between two vectors

In [71]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

distance = np.linalg.norm(a-b)
print(distance)

5.196152422706632


### 12️⃣ Find correlation coefficients between columns of a 2D array

In [72]:
arr = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])

corr = np.corrcoef(arr, rowvar=False)
print(corr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 13️⃣ Get all rows in a 2D array where the value in the second column is greater than 10

In [73]:
arr = np.array([[5, 12, 7], [8, 9, 2], [6, 15, 3]])

filtered = arr[arr[:, 1] > 10]
print(filtered)

[[ 5 12  7]
 [ 6 15  3]]


### 14️⃣ Shuffle rows of a 2D array randomly

In [74]:
arr = np.arange(9).reshape(3, 3)
np.random.shuffle(arr)
print(arr)

[[3 4 5]
 [6 7 8]
 [0 1 2]]


### 15️⃣ Replace all elements of an array greater than a certain value with a new value

In [75]:
arr = np.array([10, 45, 60, 80, 30])
arr[arr > 50] = 50
print(arr)

[10 45 50 50 30]


# 🔶 SECTION 3: Intermediate → Advanced (15 Questions)

### 1️⃣ Create a 10×3 matrix of random numbers and find row-wise maximum values

In [85]:
import numpy as np

arr = np.random.rand(10, 3)
print(arr)
row_max = arr.max(axis=1)
print(row_max)

[[0.68913304 0.90788562 0.54892518]
 [0.83942373 0.32503036 0.26212687]
 [0.97938439 0.74891143 0.2385816 ]
 [0.94306159 0.58319825 0.47512564]
 [0.39145288 0.95923309 0.78289244]
 [0.07429852 0.88808067 0.42823372]
 [0.89394392 0.42498262 0.67522712]
 [0.7181921  0.13410692 0.70852006]
 [0.26198404 0.24282854 0.60593224]
 [0.56575143 0.91778906 0.0793284 ]]
[0.90788562 0.83942373 0.97938439 0.94306159 0.95923309 0.88808067
 0.89394392 0.7181921  0.60593224 0.91778906]


### 2️⃣ Convert temperatures from Celsius to Fahrenheit using vectorized operations

In [86]:
celsius = np.array([0, 20, 37, 100])
fahrenheit = (celsius * 9 / 5) + 32
print(fahrenheit)

[ 32.   68.   98.6 212. ]


### 3️⃣ Extract every 3rd element from a 1D array

In [87]:
arr = np.arange(20)
print(arr[::3])

[ 0  3  6  9 12 15 18]


### 4️⃣ Compute (a - b) / (a + b) safely (avoid division-by-zero)

In [88]:
a = np.array([1, 2, 0, 4])
b = np.array([0, 2, 3, 4])

result = np.divide(a - b, a + b, out=np.zeros_like(a, dtype=float), where=(a + b) != 0)
print(result)

[ 1.  0. -1.  0.]


### 5️⃣ Convert a 1D array of 12 elements into 3×4 and flatten back

In [89]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
flattened = reshaped.flatten()
print(reshaped)
print(flattened)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### 6️⃣ Create a boolean mask for all even numbers

In [90]:
arr = np.arange(10)
mask = arr % 2 == 0
print(mask)

[ True False  True False  True False  True False  True False]
