# What is NumPy?
NumPy (Numerical Python) is a powerful library in Python used for numerical computing. It provides support for multi-dimensional arrays and matrices along with a large collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in scientific computing, data analysis, machine learning, and artificial intelligence due to its high performance and ease of use.

# Why is NumPy Better than Python Lists?
NumPy arrays are faster and more memory-efficient than Python lists due to the following reasons:
### Better Performance (Speed)
NumPy arrays are implemented in C and use contiguous memory blocks, making operations much faster than Python lists.
Operations on NumPy arrays are performed using vectorization, avoiding slow Python loops.
### Memory Efficiency
Python lists store each element as a separate Python object, which takes more memory.
NumPy arrays use a fixed type for elements, storing them in contiguous memory locations, reducing overhead.
### Convenience
NumPy provides built-in functions for operations like sum, mean, standard deviation, and matrix multiplication.
Python lists require explicit loops to perform these operations.

### Support for Multi-dimensional Arrays
NumPy can handle multi-dimensional arrays (1D, 2D, 3D, etc.), whereas Python lists are inefficient for handling multi-dimensional data.
### Broadcasting Feature
NumPy allows operations between arrays of different shapes (broadcasting), whereas lists require explicit looping.


In [3]:
import numpy as np

## Comparing NumPy Arrays and Lists

In [4]:
# Comparing NumPy Arrays and Lists

import time

size = 10**6

py_list = list(range(size))
np_array = np.arange(size)

# Measuring time for list multiplication
start = time.time()
py_list = [x**2 for x in py_list]
print("Python List Time", time.time() - start)

# Measuring time for numpy array multiplication
start = time.time()
np_array = np_array * 2
print("Numpy Array Time",time.time() - start)

Python List Time 0.12368106842041016
Numpy Array Time 0.001592874526977539


In [8]:
# Memory usage
import sys

py_list = list(range(1000))
np_array_int64 = np.arange(1000)
np_array_int32 = np.arange(1000).astype('int32')

print("Python list Size", sys.getsizeof(py_list))
print("Numpy Array Size with int64 numbers", sys.getsizeof(np_array_int64))
print("Numpy Array Size with int32 numbers", sys.getsizeof(np_array_int32))

Python list Size 8056
Numpy Array Size with int64 numbers 8112
Numpy Array Size with int32 numbers 4112


In [9]:
# Creating a 3x3 matrix in a Python list
py_list_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Creating a 3x3 NumPy array
np_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Python List Matrix:", py_list_matrix)
print("NumPy Matrix:\n", np_matrix)

Python List Matrix: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
NumPy Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# Vectorized Operations in Numpy
py_list = [1, 2, 3, 4, 5]
np_array = np.array([1, 2, 3, 4, 5])

# List: Requires loop
py_list_squared = [x**2 for x in py_list]

# NumPy: Uses vectorized operation
np_array_squared = np_array**2

# This will give same result but the np_array does not require loops unlike lists
print("Python List Squared:", py_list_squared)
print("NumPy Array Squared:", np_array_squared)

Python List Squared: [1, 4, 9, 16, 25]
NumPy Array Squared: [ 1  4  9 16 25]


In [12]:
# Broadcasting in Numpy
np_array = np.array([1, 2, 3, 4, 5])

# Add 10 to all the numbers of the array
print(np_array + 10) 

[11 12 13 14 15]


# Creating NumPy Arrays in Different Ways

### 1. Creating a NumPy Array from a Python List or Tuple using np.array()

In [14]:
# 👉 Use np.array() to convert lists/tuples into NumPy arrays.

# From a list
list_arr = np.array([1, 2, 3, 4, 5])

# From a tuple
tuple_arr = np.array((10, 20, 30, 40))

# From a multidimensional list
list_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("Array from list: ", list_arr)
print("Array from tuple: ", tuple_arr)
print("2d-Array: \n", list_2d)

Array from list:  [1 2 3 4 5]
Array from tuple:  [10 20 30 40]
2d-Array: 
 [[1 2 3]
 [4 5 6]]


### 2. Creating an Array with a Specific Data Type (dtype)

In [15]:
# 👉 Data types can be int, float, bool, complex, etc.
arr1 = np.array([1.5, 2.7, 3.8], dtype=int)
arr2 = np.array([1, 2, 3], dtype=float)

print(arr1)
print(arr2)

[1 2 3]
[1. 2. 3.]


### 3. Creating an Array with np.arange()

In [16]:
# 👉 Useful for generating sequences quickly.
arr = np.arange(1, 10, 2)  # Start=1, Stop=10 (exclusive), Step=2

# Default start is 0
# Default step is 1

print("Array with np.arange:", arr)

print(np.arange(21))

Array with np.arange: [1 3 5 7 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### 4. Creating an Array with np.linspace()

In [17]:
# Generates evenly spaced numbers between a start and stop.

arr = np.linspace(0, 10, 5)  #  5 equally spaced values between 0 and 10
print("Array with np.linspace: ", arr)

Array with np.linspace:  [ 0.   2.5  5.   7.5 10. ]


### 5. Creating an Array of Zeros (np.zeros()) and Ones (np.ones())

In [18]:
zeros_arr = np.zeros((2, 3))  # 2x3 matrix of zeros
ones_arr = np.ones((3, 2))  # 3x2 matrix of ones

print("Zeros array:\n", zeros_arr)
print("Ones array:\n", ones_arr)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


### 6. Creating an Identity Matrix (np.eye())

In [19]:
# Generates a square matrix with 1s on the diagonal.
identity_matrix = np.eye(4)  # 4x4 identity matrix
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 7. Creating a Random Array (np.random)

In [20]:
rand_arr1 = np.random.rand(10)  # 1d array with random valuse from 0 to 1
rand_arr2 = np.random.rand(2, 3)  # 2x3 array with random values (0 to 1)

rand_int_arr1 = np.random.randint(1, 20, 5)  # 1D array with 5 random integers (1-20)
rand_int_arr2 = np.random.randint(
    1, 100, (3, 3)
)  # 3x3 matrix with random integers (1-100)

print("Random float array1:\n", rand_arr1)
print("----------------------------------")
print("Random float array2:\n", rand_arr2)
print("----------------------------------")
print("Random integer array1:\n", rand_int_arr1)
print("----------------------------------")
print("Random integer array2:\n", rand_int_arr2)


# 👉 np.random.rand() gives floats in [0,1), while np.random.randint() gives random integers.

Random float array1:
 [0.70548923 0.17699502 0.76435896 0.96513733 0.94898409 0.46707175
 0.73557529 0.83212341 0.82269054 0.2348442 ]
----------------------------------
Random float array2:
 [[0.84628241 0.85113165 0.27519849]
 [0.70530904 0.21730606 0.61365057]]
----------------------------------
Random integer array1:
 [ 6 16 13 11 14]
----------------------------------
Random integer array2:
 [[86 36 97]
 [12 23 52]
 [ 9 16 42]]


### 8. Creating an Array with np.full()

In [21]:
filled_arr = np.full((2, 2), 7)  # 2x2 matrix filled with 7
print("Array with np.full:\n", filled_arr)

Array with np.full:
 [[7 7]
 [7 7]]


### 9. Creating a Diagonal Matrix (np.diag())

In [22]:
diag_arr = np.diag([10, 20, 30])  # Creates a diagonal matrix
print("Diagonal Matrix:\n", diag_arr)

Diagonal Matrix:
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


# NUMPY ARRAY ATTRIBUTES

## 1. ndarray.shape (Shape of an Array) :
Returns a tuple representing the dimensions of the array.

In [24]:
# Returns a tuple representing the dimensions of the array.

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape of array:", arr.shape)

Array:
 [[1 2 3]
 [4 5 6]]
Shape of array: (2, 3)


## 2. ndarray.ndim (Number of Dimensions)

Returns the number of dimensions (axes) of the array.

In [25]:
# Returns the number of dimensions (axes) of the array.

arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array dimensions:", arr_1d.ndim)
print("2D Array dimensions:", arr_2d.ndim)
print("3D Array dimensions:", arr_3d.ndim)

1D Array dimensions: 1
2D Array dimensions: 2
3D Array dimensions: 3


## 3. ndarray.size (Total Number of Elements)

Returns the total number of elements in an array.

In [26]:
# Returns the total number of elements in an array.

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Total elements in array1:", arr1.size)
print("Total elements in array2:", arr2.size)

Total elements in array1: 5
Total elements in array2: 6


## 4. ndarray.dtype (Data Type of Elements)

In [27]:
arr = np.array([1, 2, 3])
arr_float = np.array([1.2, 3.4, 5.6])

print("Data type of integer array:", arr.dtype)
print("Data type of float array:", arr_float.dtype)

Data type of integer array: int64
Data type of float array: float64


## 5. ndarray.itemsize (Size of Each Element in Bytes)

In [29]:
# Returns the memory size (in bytes) of each element.

arr = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.array([1, 2, 3], dtype=np.int64)
print("Size of each element:", arr.itemsize)
print("Size of each element:", arr2.itemsize)

Size of each element: 4
Size of each element: 8


## 6. ndarray.nbytes (Total Memory Consumption)

In [30]:
# Returns the total memory consumed by the array.

arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print("Total memory used by array:", arr.nbytes)

# 👉 nbytes = itemsize × size of the array.

Total memory used by array: 20


# NUMPY ARRAY FUNCTIONS

### 1. arr.reshape( ) - Changes the shape without changing data.

In [31]:
# np.reshape() - Changes the shape without changing data.

arr = np.array([1, 2, 3, 4, 5, 6])  # 6 elements are there in total
reshaped_arr = arr.reshape(2, 3)  # 2 rows, 3 columns
reshaped_arr2 = arr.reshape(3, -1)  # We know the number of rows(3) but we don't know the number of columns, then we can use -1
reshaped_arr3 = arr.reshape(-1, 2)  # We know the number of columns (2) but we don't know the number of rows, then we can use -1

print("Original array:", arr)
print("Reshaped array:\n", reshaped_arr)
print("Reshaped array2:\n", reshaped_arr2)
print("Reshaped array3:\n", reshaped_arr3)

# 👉 Reshape must be compatible with the number of elements.

Original array: [1 2 3 4 5 6]
Reshaped array:
 [[1 2 3]
 [4 5 6]]
Reshaped array2:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped array3:
 [[1 2]
 [3 4]
 [5 6]]


### 2. arr.ravel( ) - Converts a multi-dimensional array into 1D.

In [32]:
# np.ravel() - Converts a multi-dimensional array into 1D.

arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened = arr.ravel()

print("Flattened array:", flattened)

Flattened array: [1 2 3 4 5 6]


### 3. arr.T or arr.transpose( ) - Flips the rows and columns.

In [33]:
# np.transpose() - Flips the rows and columns.

arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed = arr.T

# 👉 T is a shortcut for transpose().

print("Original array:\n", arr)
print("Transposed array:\n", transposed)

Original array:
 [[1 2 3]
 [4 5 6]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]


### 4. np.concatenate((arr1,arr2)) - Joins two or more arrays

In [41]:
#  np.concatenate() - Joins two or more arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concat_arr = np.concatenate((arr1, arr2))

print("Concatenated array:", concat_arr)



Concatenated array: [1 2 3 4 5 6]


### 5. np.split(arr,n) - Splits an array into multiple sub-arrays.

In [39]:
# np.split() - Splits an array into multiple sub-arrays.
# 👉 Must be evenly divisible.

arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)

print("Split arrays:", split_arr)

Split arrays: [array([1, 2]), array([3, 4]), array([5, 6])]


### 6. np.unique(arr) - Finds unique elements in an array.

In [40]:
# np.unique - Finds unique elements in an array.

arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_values = np.unique(arr)

print("Unique values:", unique_values)

Unique values: [1 2 3 4 5]


# Changing Data type of a numpy array

In [42]:
# 1. Using dtype Parameter (While Creating an Array)

arr_int = np.array([1, 2, 3, 4], dtype=np.float64)  # Creating array with float dtype
print("Array:", arr_int)
print("Data type:", arr_int.dtype)

Array: [1. 2. 3. 4.]
Data type: float64


In [43]:
# 2. Using .astype() Method (Converting an Existing Array)

# The .astype() method converts an array from one data type to another without modifying the original array.

arr = np.array([1.2, 3.5, 5.8, 7.9])  # Float array
arr_int = arr.astype(np.int32)  # Converting to integer

print("Original array:", arr)
print("Converted to int:", arr_int)
print("Original Data Type:", arr.dtype)
print("New Data Type:", arr_int.dtype)

# 👉 Note: .astype() truncates decimal values instead of rounding them.

Original array: [1.2 3.5 5.8 7.9]
Converted to int: [1 3 5 7]
Original Data Type: float64
New Data Type: int32


# NUMPY OPERATIONS

## Scalar Operations

In [44]:
arr = np.array([10, 20, 30, 40])

# Scalar Addition
add_result = arr + 10  # Adds 10 to each element

# Scalar Subtraction
sub_result = arr - 5  # Subtracts 5 from each element

# Scalar Multiplication
mul_result = arr * 3  # Multiplies each element by 3

# Scalar Division
div_result = arr / 2  # Divides each element by 2

# Scalar Exponentiation
exp_result = arr**2  # Squares each element

# Scalar Modulus
mod_result = arr % 4  # Computes remainder when divided by 4

print("Addition result: ", add_result)
print("Subtraction result: ", sub_result)
print("Multiplication result: ", mul_result)
print("Division result: ", div_result)
print("Exponent result: ", exp_result)
print("Remainder result: ", mod_result)

Addition result:  [20 30 40 50]
Subtraction result:  [ 5 15 25 35]
Multiplication result:  [ 30  60  90 120]
Division result:  [ 5. 10. 15. 20.]
Exponent result:  [ 100  400  900 1600]
Remainder result:  [2 0 2 0]


## Vector Operations

In [45]:
# Operations between two NumPy arrays are performed element-wise, meaning corresponding elements are operated on.

arr1 = np.array([10, 20, 30])
arr2 = np.array([3, 2, 1])

# Vector Addition
add_result = arr1 + arr2

# Vector Subtraction
sub_result = arr1 - arr2

# Vector Multiplication
mul_result = arr1 * arr2

# Vector Division
div_result = arr1 / arr2

# Vector Exponentiation
exp_result = arr1**arr2

# Vector Modulus
mod_result = arr1 % arr2

print("Addition result: ", add_result)
print("Subtraction result: ", sub_result)
print("Multiplication result: ", mul_result)
print("Division result: ", div_result)
print("Exponent result: ", exp_result)
print("Remainder result: ", mod_result)

Addition result:  [13 22 31]
Subtraction result:  [ 7 18 29]
Multiplication result:  [30 40 30]
Division result:  [ 3.33333333 10.         30.        ]
Exponent result:  [1000  400   30]
Remainder result:  [1 0 0]


# Universal Functions

NumPy provides optimized mathematical functions (called ufuncs) that operate element-wise on arrays.

In [46]:
# np.sqrt() – Square Root

arr = np.array([4, 9, 16, 25])
result = np.sqrt(arr)

print(result)

[2. 3. 4. 5.]


In [47]:
# np.exp() – Exponential Function

arr = np.array([1, 2, 3])
result = np.exp(arr)

print(result)

[ 2.71828183  7.3890561  20.08553692]


In [48]:
#  np.log() – Natural Logarithm
arr = np.array([1, np.e, np.e**2])
result = np.log(arr)

print(result)

[0. 1. 2.]


In [49]:
# np.abs() – Absolute Values
arr = np.array([-1, -2, -3, 4])
result = np.abs(arr)

print(result)

[1 2 3 4]


# Indexing in NumPy

In [50]:
# Indexing in 1D Arrays

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # First element
print(arr[2])  # Third element
print(arr[-1])  # Last element

# Indexing starts from 0.
# Negative indexing is supported (-1 refers to the last element).

10
30
50


In [51]:
# Indexing in 2D Arrays
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D[0, 1])  # Element at row 0, column 1
print(arr2D[2, 2])  # Element at row 2, column 2

2
9


In [52]:
# Indexing in 3D Arrays
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3D)
print("----------------")
print(arr3D[1, 0, 2])  # Access element at depth 1, row 0, column 2

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------------
9


# Slicing in NumPy

Slicing allows extracting a subarray from a NumPy array using the syntax:
array[start:stop:step]

- start: Starting index (default is 0).
- stop: End index (not included).
- step: Step size (default is 1).

In [53]:
# Slicing in 1D Arrays

arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[1:5])  # Elements from index 1 to 4
print(arr[:4])  # First 4 elements
print(arr[3:])  # From index 3 to end
print(arr[::2])  # Every second element
print(arr[::-1])  # Reverse the array

[20 30 40 50]
[10 20 30 40]
[40 50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10]


In [54]:
#  Slicing in 2D Arrays
arr2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr2D[1:, 2:])  # Slice rows from index 1 onward and columns from index 2 onward
print("------------------------")
print(arr2D[:2, :3])  # First two rows, first three columns
print("------------------------")
print(arr2D[:, 1])  # All rows, second column
print("------------------------")
print(arr2D[::2, ::2])  # Every alternate row and column

[[ 7  8]
 [11 12]]
------------------------
[[1 2 3]
 [5 6 7]]
------------------------
[ 2  6 10]
------------------------
[[ 1  3]
 [ 9 11]]


In [55]:
#  Slicing in 2D Arrays
arr2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr2D[1:, 2:])  # Slice rows from index 1 onward and columns from index 2 onward
print("------------------------")
print(arr2D[:2, :3])  # First two rows, first three columns
print("------------------------")
print(arr2D[:, 1])  # All rows, second column
print("------------------------")
print(arr2D[::2, ::2])  # Every alternate row and column

[[ 7  8]
 [11 12]]
------------------------
[[1 2 3]
 [5 6 7]]
------------------------
[ 2  6 10]
------------------------
[[ 1  3]
 [ 9 11]]


In [56]:
# (c) Slicing in 3D Arrays
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3D[:, 1, :])  # All depths, second row, all columns
print(arr3D[:, :, 1])  # All depths, all rows, second column

[[ 4  5  6]
 [10 11 12]]
[[ 2  5]
 [ 8 11]]


# Advanced Indexing in NumPy: Boolean Indexing & Fancy Indexing
NumPy provides advanced indexing techniques that allow for more flexible and powerful data selection. The two most commonly used advanced indexing techniques are:
- Boolean Indexing
- Fancy Indexing (Indexing with Arrays of Indices)


## Boolean Indexing
Boolean indexing allows us to select elements from an array based on a condition.

In [57]:
arr = np.array([10, 25, 30, 45, 50])
mask = arr > 20  # Condition: Select elements greater than 20

# mask creates a Boolean array where True corresponds to values satisfying arr > 20.
# arr[mask] selects only those values.

print(mask)  # Boolean mask
print(arr[mask])  # Apply mask to select elements

[False  True  True  True  True]
[25 30 45 50]


In [58]:
# Filtering even numbers

arr = np.array([1, 2, 3, 4, 5, 6])
even_numbers = arr[arr % 2 == 0]  # Select even numbers

print(even_numbers)

[2 4 6]


In [59]:
# You can also use Boolean indexing to modify elements.

arr = np.array([10, 20, 30, 40, 50])
arr[arr > 25] = 100  # Replace elements greater than 25 with 100

print(arr)

[ 10  20 100 100 100]


In [60]:
# We can combine conditions using logical operators (&, |, ~).

arr = np.array([5, 10, 15, 20, 25, 30])
selected = arr[(arr > 10) & (arr < 30)]  # Select elements between 10 and 30
selected2 = arr[(arr < 10) | (arr > 30)]  # Select elements less than 10 or greater than 30
selected3 = arr[~(arr > 20)]  # Select elements not greater than 20

print(selected)
print(selected2)
print(selected3)

[15 20 25]
[5]
[ 5 10 15 20]


# Fancy Indexing
Fancy indexing allows us to select elements using an array of indices.

In [61]:
# Example 1: Selecting Specific Elements

arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]  # Indices of elements to select

print(arr[indices])  # Selecting elements at index 0, 2, and 4

[10 30 50]


In [62]:
# Example 2: Selecting Elements from a 2D Array
arr2D = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

rows = [0, 2]  # Select rows 0 and 2
cols = [1, 2]  # Select columns 1 and 2

print(arr2D[rows, cols])  # Fetch elements at (0,1) and (2,2)

[20 90]


In [63]:
# Example 3: Using Fancy Indexing to Modify Values
arr = np.array([100, 200, 300, 400, 500])
indices = [1, 3]  # Modify elements at index 1 and 3

arr[indices] = [999, 888]  # Assign new values
print(arr)

[100 999 300 888 500]


In [65]:
# Example 4: Reordering Elements
# Fancy indexing can also be used to reorder elements.
arr = np.array([10, 20, 30, 40, 50])
order = np.array([4, 2, 0])  # Rearrange indices

print(arr[order])

[50 30 10]


# Reshaping

In [66]:
# The .reshape() function changes the structure of an array without modifying the original data.


arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Convert to 2 rows, 3 columns

print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [67]:
# Using -1 allows NumPy to automatically calculate one dimension based on the number of elements.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_arr = arr.reshape(4, -1)  # Let NumPy determine columns

print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [68]:
#  Flattening an Array - Flattening converts a multi-dimensional array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])

flattened_arr = arr.flatten()  # Converts to 1D array
print(flattened_arr)

[1 2 3 4 5 6]


# Stacking

Stacking means joining multiple arrays along different axes.

In [69]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

h_stacked = np.hstack((arr1, arr2))  # Horizontal stacking
v_stacked = np.vstack((arr1, arr2))  # Vertical Stacking
d_stacked = np.dstack((arr1, arr2))  # Depth Stacking

print("Original arr1: \n", arr1)
print("-------------")
print("Original arr2: \n", arr2)
print("-------------")


print("Horizontal Stacking: \n", h_stacked)
print("-------------")
print("Vertical Stacking: \n", v_stacked)
print("-------------")
print("Depth Stacking: \n", d_stacked)

Original arr1: 
 [[1 2]
 [3 4]]
-------------
Original arr2: 
 [[5 6]
 [7 8]]
-------------
Horizontal Stacking: 
 [[1 2 5 6]
 [3 4 7 8]]
-------------
Vertical Stacking: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
-------------
Depth Stacking: 
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


# Splitting

Splitting is the opposite of stacking, dividing arrays into smaller sub-arrays.

In [70]:
# Splitting 1D Arrays (split)

arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)  # Split into 3 parts

print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [71]:
# Vertical Split (vsplit) -  Splits along rows.

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v_split = np.vsplit(arr2D, 3)  # Split into 3 row-wise sub-arrays

print(v_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [72]:
# Horizontal Split (hsplit) -  Splits along columns.

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
h_split = np.hsplit(arr2D, 3)  # Split into 3 column-wise sub-arrays

print(h_split)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


# Broadcasting and Vectorized Operations in NumPy

###  What is Broadcasting?
Broadcasting is a set of rules that allow NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the larger array’s shape. Broadcasting enables efficient computation, reducing memory usage and increasing speed by eliminating the need for explicit loops.

### Broadcasting Rules:

1. Make the two arrays have the same number of dimensions.
If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.
2. Make each dimension of the two arrays the same size.
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.

- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.


###Example 1 :
Let the 2 arrays sizes be (3,2) and (3,)
Add 1 to the head of the array with a smaller dimension. So, (3,) will become (1,3)
Now (1,3) is stretched from 1 to 3 to form (3,3). Remember we can only stretch 1 not other numbers

###Example 2 :
Let the 2 arrays sizes be (4,3) and (3,)
Add 1 to the head of the array with a smaller dimension. So, (3,) will become (1,3)
Now (1,3) is stretched from 1 to 4 to form (4,3). Remember we can only stretch 1 not other numbers


###Example 3 :
Let the 2 arrays sizes be (3,4) and (3,)
Add 1 to the head of the array with a smaller dimension. So, (3,) will become (1,3)
Now (1,3) is stretched from 1 to 3 to form (3,3). Remember we can only stretch 1 not other numbers
Now the array sizes are different. One is (3,4) and the newly stretched one is (3,3).
So, broadcasting will not be possible here


###Example 4 :
Let the 2 arrays sizes be (3,1) and (1,3).
(1,3) can be broadcasted to (3,3) by stretching 1 to 3.
Similarly (3,1) can be broadcasted to (3,3) by stretching 1 to 3.


In [73]:
# Example 1: Adding a Scalar to an Array
arr = np.array([1, 2, 3, 4])
result = arr + 10  # Broadcasting: Add 10 to each element

print(result)

[11 12 13 14]


In [76]:
# Example 2: Broadcasting a 1D Array to a 2D Array
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
arr1D = np.array([1, 2, 3])

print(arr2D)
print(arr1D)
result = arr2D + arr1D  # Broadcasting arr1D across arr2D
print(result)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[[2 4 6]
 [5 7 9]]


In [77]:
# Example 3: Broadcasting in Multi-Dimensional Arrays
arr3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr1D = np.array([10, 20])

result = arr3D + arr1D  # Broadcasting arr1D across arr3D
print(result)

[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


#  Working with Mathematical Formulae in NumPy
Mathematical Functions in NumPy.
NumPy supports a wide range of mathematical operations directly on arrays, including trigonometric functions, exponential functions, logarithmic operations, and more. These operations are vectorized, meaning they apply to each element of the array without the need for explicit loops.

# Common Mathematical Functions in NumPy:
- np.sin(), np.cos(), np.tan() — Trigonometric functions.
- np.exp(), np.log(), np.log10() — Exponential and logarithmic functions.
- np.sqrt() — Square root.
- np.power() — Element-wise power.
- np.abs() — Absolute value.
- np.sum(), np.prod() — Sum and product of elements.
- np.mean(), np.median(), np.std() — Statistical functions.

In [79]:
# Example 1: Trigonometric Functions

# Array of angles (in radians)
angles = np.array([0, np.pi/4, np.pi/2, np.pi])

# Applying trigonometric functions
sin_vals = np.sin(angles)
cos_vals = np.cos(angles)

print("Sine values:", sin_vals)
print("Cosine values:", cos_vals)

Sine values: [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
Cosine values: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]


In [80]:
# Example 2: Exponential and Logarithmic Functions
arr = np.array([1, 2, 3, 4])

# Applying exponential and logarithmic functions
exp_vals = np.exp(arr)
log_vals = np.log(arr)

print("Exponential values:", exp_vals)
print("Logarithmic values:", log_vals)

Exponential values: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Logarithmic values: [0.         0.69314718 1.09861229 1.38629436]


In [81]:
# Example 3: Power and Absolute Functions
arr = np.array([1, -2, 3, -4])

# Applying power and absolute functions
squared_vals = np.power(arr, 2)
abs_vals = np.abs(arr)

print("Squared values:", squared_vals)
print("Absolute values:", abs_vals)

Squared values: [ 1  4  9 16]
Absolute values: [1 2 3 4]


In [82]:
# Example 4: Applying Mathematical Formulae on Arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Applying a mathematical formula: (arr1^2 + arr2^2)
result = np.sqrt(arr1**2 + arr2**2)

print("Result:", result)

Result: [4.12310563 5.38516481 6.70820393]


In [83]:
# Find mean, median and standard deviation

arr = np.arange(100)

print("Mean is :", np.mean(arr))
print("Median is :", np.median(arr))
print("Standard Deviation is :", np.std(arr))
print("Variance is :", np.var(arr))

Mean is : 49.5
Median is : 49.5
Standard Deviation is : 28.86607004772212
Variance is : 833.25


# Difference Between axis=0 and axis=1 in NumPy

## In NumPy, the axis parameter determines the direction of operations like sum(), mean(), all(), etc.

 - axis=0 → Operates along columns (vertical direction)
 - axis=1 → Operates along rows (horizontal direction)

In [84]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
# Example: Sum Across Columns
col_sum = np.sum(arr, axis=0)
print("Column wise sum ", col_sum)

print("----------------------------")

# Example: Sum Across Rows
row_sum = np.sum(arr, axis=1)
print("Row wise sum ", row_sum)

print("----------------------------")

print("Max per column", np.max(arr, axis=0))  # Max per column
print("Max per row", np.max(arr, axis=1))  # Max per row
print("Min per column", np.min(arr, axis=0))  # Min per column
print("Min per row", np.min(arr, axis=1))  # Min per row

Column wise sum  [12 15 18]
----------------------------
Row wise sum  [ 6 15 24]
----------------------------
Max per column [7 8 9]
Max per row [3 6 9]
Min per column [1 2 3]
Min per row [1 4 7]


In [86]:
# Example : Checking all() with axis
bool_arr = np.array([[True, False, True], [True, True, True], [False, True, True]])

print(np.all(bool_arr, axis=0))  # Checks all values in each column
print(np.all(bool_arr, axis=1))  # Checks all values in each row

[False False  True]
[False  True False]


📌 Key Takeaways
- ✅ axis=0 → Column-wise operations (go down)
- ✅ axis=1 → Row-wise operations (go across)
- ✅ Works for various NumPy functions like sum(), mean(), min(), max(), all(), etc.

# WHERE AND ANY

## WHERE

In [88]:
# Examples of Where
# Example 1: Finding indices where a condition is met
arr = np.array([10, 20, 30, 40, 50])
indices = np.where(arr > 25)  # Find indices where elements are greater than 25
print(indices)

(array([2, 3, 4]),)


In [89]:
# Example 2: Replacing values based on a condition
arr = np.array([10, 20, 30, 40, 50])
new_arr = np.where(arr > 25, 1, 0)  # Replace values > 25 with 1, else 0
print(new_arr)

[0 0 1 1 1]


In [90]:
# Example 3: Using where to select between two arrays

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

condition = a > 3  # Condition to check

result = np.where(condition, a, b)  # Select elements from a where condition is True, else from b
print(result)

[10 20 30  4  5]


## ANY

In [91]:
# Examples of Any
# Example 1: Checking if any element is True
arr = np.array([0, 0, 1, 0])
result = np.any(arr)  # Returns True if at least one element is nonzero
print(result)

True


In [92]:
# Example 2: Using any() along an axis
arr = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]])

result = np.any(arr, axis=0)  # Checks if any value is nonzero in each column
print(result)

[False  True False]


In [94]:
# Example 3: Checking conditions with any()
arr = np.array([10, 20, 30, 40])
condition = arr > 25
print(condition)  # [False False  True  True]
print(np.any(condition))  # True, because at least one element is > 25


print(np.any(arr<100))
print(np.any(arr>30))

[False False  True  True]
True
True
True


## ALL

In [95]:
# Example 1: Checking if all elements are nonzero

arr = np.array([1, 2, 3, 4, 5])
result = np.all(arr)  # Checks if all elements are nonzero
print(result)

True


In [96]:
# Example 2: If there's a zero in the array
arr = np.array([1, 2, 0, 4, 5])
result = np.all(arr)
print(result)

# Here, since there's a 0, np.all() returns False.

False


In [97]:
# Example 3: Checking a Condition
arr = np.array([10, 20, 30, 40])
result = np.all(arr > 5)  # Are all elements greater than 5?
print(result)

True


In [98]:
# Example 4: Using axis Parameter
arr = np.array([[1, 2, 3], [0, 5, 6]])

result = np.all(arr, axis=0)  # Check column-wise
print(result)

[False  True  True]


In [101]:
# Example 5: all() 
arr = np.array([[1, 2, 3], [4, 5, 6]])

result = np.all(arr > 0, axis=1)
print(result)

[ True  True]


# 2. Handling Missing Values in NumPy
In real-world data, missing or NaN (Not a Number) values are common. NumPy provides tools to detect, replace, and ignore these NaN values during computations.
Key Functions to Handle Missing Data:
- np.isnan() — Detects NaN values.
- np.nanmean(), np.nanstd(), np.nanmedian() — Compute mean, standard deviation, and median, ignoring NaN values.
- np.nan_to_num() — Replaces NaN values with a specified value.

In [102]:
# Example 1: Detecting NaN Values

arr = np.array([1, np.nan, 3, 4, np.nan])

# Checking for NaN values
nan_check = np.isnan(arr)

print("NaN detection:", nan_check)

NaN detection: [False  True False False  True]


In [103]:
# Example 2: Ignoring NaN Values in Computations

arr = np.array([1, np.nan, 3, 4, np.nan])

# Compute mean, ignoring NaN values
mean_val = np.nanmean(arr)
print("Mean ignoring NaNs:", mean_val)

Mean ignoring NaNs: 2.6666666666666665


In [104]:
# Example 3: Replacing NaN with a Specific Value
# You can replace NaN values using np.nan_to_num().
arr = np.array([1, np.nan, 3, 4, np.nan])

# Replace NaN values with 0
arr_cleaned = np.nan_to_num(arr, nan=0)
print("Array with NaN replaced:", arr_cleaned)

Array with NaN replaced: [1. 0. 3. 4. 0.]


In [105]:
# Example 4: Fill NaN with Interpolation or Mean (Custom Handling)
# In some cases, you may want to fill NaN values with a calculated value like the mean of the array.
arr = np.array([1, np.nan, 3, 4, np.nan])

# Replace NaN with the mean of non-NaN values
mean_val = np.nanmean(arr)
arr_filled = np.where(np.isnan(arr), mean_val, arr)

print("Array with NaN replaced by mean:", arr_filled)

Array with NaN replaced by mean: [1.         2.66666667 3.         4.         2.66666667]


# Some more important Numpy Functions :

In [106]:
# 1. np.sort() - Sorts an array in ascending order.
# Usage: When you need to sort your data (e.g., for analysis or presentation).


arr = np.array([3, 1, 4, 2])

sorted_arr = np.sort(arr)

print("Sorted array:", sorted_arr)

Sorted array: [1 2 3 4]


In [107]:
# 2. np.append() - Appends values to the end of an array.
# Usage: To add elements to the end of an existing array.

arr = np.array([1, 2, 3])
arr_appended = np.append(arr, [4, 5])

print("Array after append:", arr_appended)

Array after append: [1 2 3 4 5]


In [108]:
# 3. np.concatenate() - Joins two or more arrays along a specified axis.
# Usage: When you need to merge multiple arrays.

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

concatenated_arr = np.concatenate((arr1, arr2))

print("Concatenated array:", concatenated_arr)

Concatenated array: [1 2 3 4]


In [109]:
# 4. np.unique() - Returns the sorted unique elements of an array.
# Usage: To get distinct elements in an array, useful for identifying categories.

arr = np.array([1, 2, 2, 3, 4, 4, 4])

unique_vals = np.unique(arr)

print("Unique values:", unique_vals)

Unique values: [1 2 3 4]


In [110]:
# 5. np.expand_dims() - Expands the shape of an array by adding a new axis.
# Usage: To add a new dimension to an array, useful in operations like broadcasting.

arr = np.array([1, 2, 3])
expanded_arr = np.expand_dims(arr, axis=0)

print("Expanded array:", expanded_arr)

Expanded array: [[1 2 3]]


In [111]:
# 6. np.where() - Returns elements chosen from x or y depending on the condition.
# Usage: For conditional logic based on arrays.

arr = np.array([1, 2, 3, 4])
result = np.where(arr > 2, arr, 0)

print("Result after where condition:", result)

Result after where condition: [0 0 3 4]


In [112]:
# 7. np.argmax() - Returns the index of the maximum value in an array.
# Usage: To find the position of the highest value, useful in tasks like classification (e.g., finding the most likely class).

arr = np.array([1, 5, 3, 2])
max_index = np.argmax(arr)

print("Index of max value:", max_index)

Index of max value: 1


In [113]:
# 8. np.cumsum() - Computes the cumulative sum of elements in an array.
# Usage: To get the running total or cumulative sum.

arr = np.array([1, 2, 3, 4])
cumsum_arr = np.cumsum(arr)

print("Cumulative sum:", cumsum_arr)

Cumulative sum: [ 1  3  6 10]


In [114]:
# 9. np.percentile() - Computes the nth percentile of the array.
# Usage: To compute a specific percentile value, useful for statistical analysis.

arr = np.array([1, 2, 3, 4, 5])
percentile_50 = np.percentile(arr, 50)

print("50th percentile:", percentile_50)

50th percentile: 3.0


In [115]:
# 10. np.histogram() - Computes the histogram of a dataset.
# Usage: To visualize the distribution of data.

arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
hist, bins = np.histogram(arr, bins=4)

print("Histogram:", hist)
print("Bins:", bins)

Histogram: [1 2 3 4]
Bins: [1.   1.75 2.5  3.25 4.  ]


In [116]:
# 11. np.corrcoef() - Computes the Pearson correlation coefficient of two arrays.
# Usage: To measure the linear correlation between two variables.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
corr = np.corrcoef(arr1, arr2)
print("Correlation coefficient matrix:", corr)

Correlation coefficient matrix: [[1. 1.]
 [1. 1.]]


In [117]:
# 12. np.isin() - Checks if elements of one array are present in another array.
# Usage: Useful for filtering or checking membership.

arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3, 4])

result = np.isin(arr1, arr2)

print("Is in result:", result)

Is in result: [False  True  True]


In [118]:
# 13. np.flip() - Flips the elements of an array along a specified axis.
# Usage: Useful when reversing the order of elements.


arr = np.array([1, 2, 3, 4])
flipped_arr = np.flip(arr)

print("Flipped array:", flipped_arr)

Flipped array: [4 3 2 1]


In [119]:
# 14. np.put() - Place values at specified indices in an array.
# Usage: For modifying specific indices in an array.

arr = np.array([1, 2, 3, 4])
np.put(arr, [1, 3], [10, 20])  # Replace index 1 with 10 and index 3 with 20

print("Array after put:", arr)

Array after put: [ 1 10  3 20]


In [120]:
# 15. np.delete() - Deletes elements from an array along a specified axis.
# Usage: To remove unwanted values or indices from an array.

arr = np.array([10, 20, 30, 40])
arr_deleted = np.delete(arr, [1, 3])  # It deletes the elements with index 1 and 3

print("Array after delete:", arr_deleted)

Array after delete: [10 30]


In [121]:
# 16. np.union1d() - Finds the union of two arrays.
# Usage: To combine two arrays and remove duplicates.

arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 4, 5])

union_arr = np.union1d(arr1, arr2)
print("Union of arrays:", union_arr)

Union of arrays: [1 2 3 4 5]


In [122]:
# 17. np.intersect1d() - Finds the intersection of two arrays.
# Usage: To find common elements between two arrays.

arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 4, 5])

intersection_arr = np.intersect1d(arr1, arr2)
print("Intersection of arrays:", intersection_arr)

Intersection of arrays: [3]


In [123]:
# 18. np.setdiff1d() - Finds the difference between two arrays (elements in the first array but not in the second).
# Usage: To find elements unique to the first array.

arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 4, 5])

diff_arr = np.setdiff1d(arr1, arr2)

print("Difference of arrays:", diff_arr)

Difference of arrays: [1 2]


In [124]:
# 19. np.setxor1d() - Finds the symmetric difference between two arrays (elements in either of the arrays but not both).
# Usage: To find unique elements in either of the arrays.

arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 4, 5])
symmetric_diff = np.setxor1d(arr1, arr2)
print("Symmetric difference of arrays:", symmetric_diff)

Symmetric difference of arrays: [1 2 4 5]


In1d result: [False  True  True]


/var/folders/2b/11ybmfpn3pv3vyjdgtk0ss7m0000gn/T/ipykernel_14261/1342987212.py:8: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  result = np.in1d(arr1, arr2)


In [126]:
# 21. np.clip() - Clips the values in an array to a specified range.
# Usage: Useful for limiting extreme values in data.

arr = np.array([1, 5, 10, 15, 20])

clipped_arr = np.clip(arr, 5, 15)

print("Clipped array:", clipped_arr)

Clipped array: [ 5  5 10 15 15]


In [127]:
# 22. np.tile() - Constructs an array by repeating the input array.
# Usage: To create a repeated version of an array.

arr = np.array([1, 2])
tiled_arr = np.tile(arr, 3)

print("Tiled array:", tiled_arr)

Tiled array: [1 2 1 2 1 2]


In [128]:
# 23. np.repeat() - Repeats elements of an array.
# Usage: For creating an array with repeated elements.

arr = np.array([1, 2])
repeated_arr = np.repeat(arr, 3)

print("Repeated array:", repeated_arr)

Repeated array: [1 1 1 2 2 2]


In [129]:
# 24. np.uniform() - Generates random samples from a uniform distribution.
# Usage: For generating random numbers within a specified range.

rand_arr = np.random.uniform(0, 10, 5)

print("Random uniform array:", rand_arr)

Random uniform array: [6.93248002 0.64367669 0.11794151 9.74256674 3.82838371]


In [130]:
# 25. np.allclose() - Checks if two arrays are element-wise equal within a tolerance.
# Usage: Useful for comparing floating-point arrays.

arr1 = np.array([1.0, 2.0])
arr2 = np.array([1.0, 2.00000001])

are_close = np.allclose(arr1, arr2)

print("Arrays are close:", are_close)

Arrays are close: True


In [131]:
# 26. np.array_equal() - Checks if two arrays have the same shape and elements.
# Usage: To compare two arrays element-wise.

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

are_equal = np.array_equal(arr1, arr2)

print("Arrays are equal:", are_equal)

Arrays are equal: True


In [132]:
# 27. np.swapaxes() - Swaps the axes of an array.
# Usage: Useful for changing the shape of multi-dimensional arrays.

arr = np.array([[1, 2], [3, 4]])
swapped_arr = np.swapaxes(arr, 0, 1)

print("Swapped axes array:", swapped_arr)

Swapped axes array: [[1 3]
 [2 4]]
